function makeGroup(letter){return[{name:`${letter} Team 1`,wins:0,losses:0,diff:0},{name:`${letter} Team 2`,wins:0,losses:0,diff:0},{name:`${letter} Team 3`,wins:0,losses:0,diff:0},{name:`${letter} Team 4`,wins:0,losses:0,diff:0}]}
function makeMatches(){const labels={UB1:"Upper Round 1 - Match 1",UB2:"Upper Round 1 - Match 2",UB3:"Upper Round 1 - Match 3",UB4:"Upper Round 1 - Match 4",UB5:"Upper Semifinal 1",UB6:"Upper Semifinal 2",UB7:"Upper Final",LB1:"Lower Round 1 - Match 1",LB2:"Lower Round 1 - Match 2",LB3:"Lower Round 2 - Match 1",LB4:"Lower Round 2 - Match 2",LB5:"Lower Final",GF:"Grand Final"};const out={};Object.entries(labels).forEach(([id,label])=>out[id]={id,label,team1:"TBD",team2:"TBD",score1:0,score2:0,bestOf:5,winner:null});return out}
const defaultState=()=>({settings:{groupsTitle:"GROUPS",groupsLeft:"LEAGUE OF LEGENDS",groupsRight:"WORLD CHAMPIONSHIP",playoffsTitle:"DOUBLE ELIMINATION",playoffsLeft:"WORLDS 2025",playoffsRight:"PLAYOFFS",upperLabel:"WINNER BRACKET",lowerLabel:"LOSER BRACKET",footerText:"ALL SERIES ARE BEST OF 5",backgroundLogo:""},teamLogos:{},groups:{A:makeGroup("A"),B:makeGroup("B"),C:makeGroup("C"),D:makeGroup("D")},matches:makeMatches()});
let state=loadState(),currentTab="groups",editMatchId=null;
const el=id=>document.getElementById(id);
const refs={groupsView:el("groupsView"),playoffsView:el("playoffsView"),tabGroupsBtn:el("tabGroupsBtn"),tabPlayoffsBtn:el("tabPlayoffsBtn"),groupsGrid:el("groupsGrid"),bracketSvg:el("bracketSvg"),bracketCards:el("bracketCards"),groupsHeaderTitle:el("groupsHeaderTitle"),groupsHeaderLeft:el("groupsHeaderLeft"),groupsHeaderRight:el("groupsHeaderRight"),playoffsHeaderTitle:el("playoffsHeaderTitle"),playoffsHeaderLeft:el("playoffsHeaderLeft"),playoffsHeaderRight:el("playoffsHeaderRight"),upperBracketLabel:el("upperBracketLabel"),lowerBracketLabel:el("lowerBracketLabel"),footerText:el("footerText"),playoffsBgLogo:el("playoffsBgLogo"),saveStateBtn:el("saveStateBtn"),loadStateBtn:el("loadStateBtn"),loadStateInput:el("loadStateInput"),modalBackdrop:el("modalBackdrop"),modalTitle:el("modalTitle"),modalTeam1Label:el("modalTeam1Label"),modalTeam2Label:el("modalTeam2Label"),modalScore1:el("modalScore1"),modalScore2:el("modalScore2"),modalCancelBtn:el("modalCancelBtn"),modalSaveBtn:el("modalSaveBtn"),groupsTitleInput:el("groupsTitleInput"),groupsLeftInput:el("groupsLeftInput"),groupsRightInput:el("groupsRightInput"),playoffsTitleInput:el("playoffsTitleInput"),playoffsLeftInput:el("playoffsLeftInput"),playoffsRightInput:el("playoffsRightInput"),upperLabelInput:el("upperLabelInput"),lowerLabelInput:el("lowerLabelInput"),footerTextInput:el("footerTextInput"),bgLogoInput:el("bgLogoInput"),teamLogoSelect:el("teamLogoSelect"),teamLogoInput:el("teamLogoInput")};
function loadState(){try{const raw=localStorage.getItem("broadcastBracketWebState");return raw?JSON.parse(raw):defaultState()}catch{return defaultState()}}
function persist(){localStorage.setItem("broadcastBracketWebState",JSON.stringify(state))}
function rankGroup(group){return [...group].sort((a,b)=>(b.wins*3-a.wins*3)||(b.diff-a.diff)||(a.losses-b.losses)||a.name.localeCompare(b.name))}
function computeWinner(m){if(m.team1==="TBD"||m.team2==="TBD")m.winner=null;else if(m.score1>m.score2)m.winner=1;else if(m.score2>m.score1)m.winner=2;else m.winner=null}
function winnerOf(m){return m.winner===1?m.team1:m.winner===2?m.team2:"TBD"}
function loserOf(m){return m.winner===1?m.team2:m.winner===2?m.team1:"TBD"}
function seedFromGroups(){const ranked={A:rankGroup(state.groups.A),B:rankGroup(state.groups.B),C:rankGroup(state.groups.C),D:rankGroup(state.groups.D)},m=state.matches;m.UB1.team1=ranked.A[0]?.name||"TBD";m.UB1.team2=ranked.B[1]?.name||"TBD";m.UB2.team1=ranked.B[0]?.name||"TBD";m.UB2.team2=ranked.A[1]?.name||"TBD";m.UB3.team1=ranked.C[0]?.name||"TBD";m.UB3.team2=ranked.D[1]?.name||"TBD";m.UB4.team1=ranked.D[0]?.name||"TBD";m.UB4.team2=ranked.C[1]?.name||"TBD";Object.keys(m).forEach(id=>{if(!["UB1","UB2","UB3","UB4"].includes(id)){m[id].team1="TBD";m[id].team2="TBD"}m[id].score1=0;m[id].score2=0;computeWinner(m[id])});propagateBracket()}
function propagateBracket(){const m=state.matches;Object.values(m).forEach(computeWinner);m.UB5.team1=winnerOf(m.UB1);m.UB5.team2=winnerOf(m.UB2);computeWinner(m.UB5);m.UB6.team1=winnerOf(m.UB3);m.UB6.team2=winnerOf(m.UB4);computeWinner(m.UB6);m.UB7.team1=winnerOf(m.UB5);m.UB7.team2=winnerOf(m.UB6);computeWinner(m.UB7);m.LB1.team1=loserOf(m.UB1);m.LB1.team2=loserOf(m.UB2);computeWinner(m.LB1);m.LB2.team1=loserOf(m.UB3);m.LB2.team2=loserOf(m.UB4);computeWinner(m.LB2);m.LB3.team1=winnerOf(m.LB1);m.LB3.team2=loserOf(m.UB5);computeWinner(m.LB3);m.LB4.team1=winnerOf(m.LB2);m.LB4.team2=loserOf(m.UB6);computeWinner(m.LB4);m.LB5.team1=winnerOf(m.LB3);m.LB5.team2=winnerOf(m.LB4);computeWinner(m.LB5);m.GF.team1=winnerOf(m.UB7);m.GF.team2=winnerOf(m.LB5);computeWinner(m.GF)}
function applySettingsToInputs(){refs.groupsTitleInput.value=state.settings.groupsTitle;refs.groupsLeftInput.value=state.settings.groupsLeft;refs.groupsRightInput.value=state.settings.groupsRight;refs.playoffsTitleInput.value=state.settings.playoffsTitle;refs.playoffsLeftInput.value=state.settings.playoffsLeft;refs.playoffsRightInput.value=state.settings.playoffsRight;refs.upperLabelInput.value=state.settings.upperLabel;refs.lowerLabelInput.value=state.settings.lowerLabel;refs.footerTextInput.value=state.settings.footerText}
function renderHeaders(){refs.groupsHeaderTitle.textContent=state.settings.groupsTitle;refs.groupsHeaderLeft.textContent=state.settings.groupsLeft;refs.groupsHeaderRight.textContent=state.settings.groupsRight;refs.playoffsHeaderTitle.textContent=state.settings.playoffsTitle;refs.playoffsHeaderLeft.textContent=state.settings.playoffsLeft;refs.playoffsHeaderRight.textContent=state.settings.playoffsRight;refs.upperBracketLabel.textContent=state.settings.upperLabel;refs.lowerBracketLabel.textContent=state.settings.lowerLabel;refs.footerText.textContent=state.settings.footerText;refs.playoffsBgLogo.style.backgroundImage=state.settings.backgroundLogo?`url(${state.settings.backgroundLogo})`:"none"}
function renderGroups(){refs.groupsGrid.innerHTML="";["A","B","C","D"].forEach(key=>{const group=rankGroup(state.groups[key]);const card=document.createElement("div");card.className="group-card";card.innerHTML=`<div class="group-card-header"><div>GROUP ${key}</div><div>W - L</div></div><table class="group-table"><thead><tr><th class="team-col">Team</th><th>W</th><th>L</th><th>Diff</th></tr></thead><tbody></tbody></table>`;const tbody=card.querySelector("tbody");group.forEach((team,idx)=>{const tr=document.createElement("tr");const logo=state.teamLogos[team.name]||"";tr.innerHTML=`<td class="team-cell"><div class="team-row-wrap">${logo?`<img class="team-logo" src="${logo}" alt="">`:`<div class="logo-placeholder"></div>`}<input class="team-name-input" data-group="${key}" data-row="${idx}" data-field="name" value="${escapeAttr(team.name)}"></div></td><td class="num-cell"><input data-group="${key}" data-row="${idx}" data-field="wins" type="number" min="0" max="99" value="${team.wins}"></td><td class="num-cell"><input data-group="${key}" data-row="${idx}" data-field="losses" type="number" min="0" max="99" value="${team.losses}"></td><td class="num-cell"><input data-group="${key}" data-row="${idx}" data-field="diff" type="number" min="-99" max="99" value="${team.diff}"></td>`;tbody.appendChild(tr)});refs.groupsGrid.appendChild(card)});refs.groupsGrid.querySelectorAll("input[data-group]").forEach(input=>input.addEventListener("change",onGroupInputChange))}
function onGroupInputChange(e){const {group,row,field}=e.target.dataset;const ranked=rankGroup(state.groups[group]);const team=ranked[Number(row)];if(!team)return;if(field==="name"){const oldName=team.name;team.name=e.target.value||oldName;if(state.teamLogos[oldName]&&!state.teamLogos[team.name])state.teamLogos[team.name]=state.teamLogos[oldName]}else team[field]=Number(e.target.value||0);state.groups[group]=ranked;seedFromGroups();persist();renderAll()}
function buildLogoSelect(){refs.teamLogoSelect.innerHTML="";Object.values(state.groups).flat().map(t=>t.name).forEach(name=>{const opt=document.createElement("option");opt.value=name;opt.textContent=name;refs.teamLogoSelect.appendChild(opt)})}
function renderBracket(){const positions={UB1:[35,150],UB2:[35,355],UB3:[35,660],UB4:[35,865],UB5:[620,245],UB6:[620,755],UB7:[1210,500],LB1:[35,1070],LB2:[35,1230],LB3:[620,1070],LB4:[620,1230],LB5:[1210,1150],GF:[1800,1150]};refs.bracketCards.innerHTML="";refs.bracketSvg.innerHTML="";const lines=[["UB1","UB5"],["UB2","UB5"],["UB3","UB6"],["UB4","UB6"],["UB5","UB7"],["UB6","UB7"],["LB1","LB3"],["LB2","LB4"],["LB3","LB5"],["LB4","LB5"],["UB7","GF"],["LB5","GF"]];lines.forEach(([a,b])=>{const [ax,ay]=positions[a],[bx,by]=positions[b],startX=ax+440,startY=ay+49,endX=bx,endY=by+49,midX=Math.round((startX+endX)/2);const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d",`M ${startX} ${startY} L ${midX} ${startY} L ${midX} ${endY} L ${endX} ${endY}`);path.setAttribute("stroke","rgba(255,255,255,.65)");path.setAttribute("stroke-width","3");path.setAttribute("fill","none");refs.bracketSvg.appendChild(path)});Object.entries(positions).forEach(([id,[x,y]])=>{const match=state.matches[id];const card=document.createElement("div");card.className="match-card";card.style.left=`${x}px`;card.style.top=`${y}px`;card.innerHTML=renderMatchRows(match);card.addEventListener("click",()=>openMatchModal(id));refs.bracketCards.appendChild(card)})}
function renderMatchRows(match){return[1,2].map(slot=>{const team=match[`team${slot}`],score=match[`score${slot}`],winner=match.winner===slot,logo=state.teamLogos[team]||"";return `<div class="match-row ${winner?"winner":""}">${logo?`<img class="match-logo" src="${logo}" alt="">`:`<div class="match-placeholder"></div>`}<div class="match-name">${escapeHtml(team.toUpperCase())}</div><div class="match-score">${score}</div></div>`}).join("")}
function openMatchModal(id){editMatchId=id;const match=state.matches[id];refs.modalTitle.textContent=match.label;refs.modalTeam1Label.textContent=match.team1;refs.modalTeam2Label.textContent=match.team2;refs.modalScore1.value=match.score1;refs.modalScore2.value=match.score2;refs.modalBackdrop.classList.remove("hidden")}
function closeMatchModal(){editMatchId=null;refs.modalBackdrop.classList.add("hidden")}
function saveMatchModal(){if(!editMatchId)return;const match=state.matches[editMatchId];match.score1=Number(refs.modalScore1.value||0);match.score2=Number(refs.modalScore2.value||0);computeWinner(match);propagateBracket();persist();renderBracket();closeMatchModal()}
function switchTab(tab){currentTab=tab;refs.groupsView.classList.toggle("active",tab==="groups");refs.playoffsView.classList.toggle("active",tab==="playoffs");refs.tabGroupsBtn.classList.toggle("active",tab==="groups");refs.tabPlayoffsBtn.classList.toggle("active",tab==="playoffs")}
function wireSettings(){[["groupsTitleInput","groupsTitle"],["groupsLeftInput","groupsLeft"],["groupsRightInput","groupsRight"],["playoffsTitleInput","playoffsTitle"],["playoffsLeftInput","playoffsLeft"],["playoffsRightInput","playoffsRight"],["upperLabelInput","upperLabel"],["lowerLabelInput","lowerLabel"],["footerTextInput","footerText"]].forEach(([id,key])=>refs[id].addEventListener("input",e=>{state.settings[key]=e.target.value;persist();renderHeaders()}));refs.bgLogoInput.addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;state.settings.backgroundLogo=await fileToDataUrl(file);persist();renderHeaders()});refs.teamLogoInput.addEventListener("change",async e=>{const file=e.target.files?.[0],team=refs.teamLogoSelect.value;if(!file||!team)return;state.teamLogos[team]=await fileToDataUrl(file);persist();renderAll()})}
function saveJson(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="broadcast_tournament_web.json";a.click();URL.revokeObjectURL(a.href)}
function loadJsonFile(file){const reader=new FileReader();reader.onload=()=>{try{state=JSON.parse(reader.result);persist();buildLogoSelect();seedFromGroups();applySettingsToInputs();renderAll()}catch{alert("Invalid JSON file.")}};reader.readAsText(file)}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}
function escapeHtml(str){return String(str).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function escapeAttr(str){return escapeHtml(str).replaceAll("'","&#39;")}
function renderAll(){renderHeaders();renderGroups();renderBracket();buildLogoSelect()}
refs.tabGroupsBtn.addEventListener("click",()=>switchTab("groups"));refs.tabPlayoffsBtn.addEventListener("click",()=>switchTab("playoffs"));refs.modalCancelBtn.addEventListener("click",closeMatchModal);refs.modalSaveBtn.addEventListener("click",saveMatchModal);refs.saveStateBtn.addEventListener("click",saveJson);refs.loadStateBtn.addEventListener("click",()=>refs.loadStateInput.click());refs.loadStateInput.addEventListener("change",e=>{const file=e.target.files?.[0];if(file)loadJsonFile(file)});
wireSettings();seedFromGroups();applySettingsToInputs();renderAll();switchTab("groups");persist();
